services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    user: "admin_vp"
    ports:
      - "8080:8080"
    networks:
      app-network:
  mysqldatabase:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      app-network:
  memcahce:
    image: memcached:trixie    
    networks:
      app-network:

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    networks:
      app-network:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      app-network:
    ports:
      - "5000:80"
    
networks:
  app-network:
volumes:
  mysqldata:
  